baseURL: "https://www.elfinjohn.com/"
languageCode: en-us
title: John Williams, Web Developer

permalinks:
  blog: "/:year/:month/:slug"

params:
  homeText: Not really a designer, tbh.
  dateFormat: Jan 2, 2006

taxonomies:
  tag: tags

# This configures the markdown renderer. We accept all the default 
# behavior except stripping HTML out of the content. 
markup: 
  goldmark:
    renderer:
      unsafe: true


menu:
  main:
  # name: About
  # url: /about/
  - name: Blog
    url: /blog/
  # name: Projects
  # url: /projects/
  # name: Experiments
  # url: /experiments/
